const MAX_SERVICE_FILES_PER_UPLOAD = 100;
const MAX_LEGACY_UPDATE_FILES_PER_UPLOAD = 20;
const MAX_UPLOAD_FILE_SIZE_BYTES = 5 * 1024 * 1024;

module.exports = {
  MAX_SERVICE_FILES_PER_UPLOAD,
  MAX_LEGACY_UPDATE_FILES_PER_UPLOAD,
  MAX_UPLOAD_FILE_SIZE_BYTES,
};
